/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as DashboardIndexImport } from './pages/dashboard/index'
import { Route as userIndexImport } from './pages/(user)/index'
import { Route as userPrivacyImport } from './pages/(user)/privacy'
import { Route as userHomeImport } from './pages/(user)/home'
import { Route as userFaqImport } from './pages/(user)/faq'
import { Route as userContactImport } from './pages/(user)/contact'

// Create/Update Routes

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const userIndexRoute = userIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const userPrivacyRoute = userPrivacyImport.update({
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const userHomeRoute = userHomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const userFaqRoute = userFaqImport.update({
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const userContactRoute = userContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(user)/contact': {
      preLoaderRoute: typeof userContactImport
      parentRoute: typeof rootRoute
    }
    '/(user)/faq': {
      preLoaderRoute: typeof userFaqImport
      parentRoute: typeof rootRoute
    }
    '/(user)/home': {
      preLoaderRoute: typeof userHomeImport
      parentRoute: typeof rootRoute
    }
    '/(user)/privacy': {
      preLoaderRoute: typeof userPrivacyImport
      parentRoute: typeof rootRoute
    }
    '/(user)/': {
      preLoaderRoute: typeof userIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  userContactRoute,
  userFaqRoute,
  userHomeRoute,
  userPrivacyRoute,
  userIndexRoute,
  DashboardIndexRoute,
])

/* prettier-ignore-end */
